# Generated by Django 5.0.6 on 2024-06-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_alter_request_response_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='request',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='request',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='region'),
        ),
    ]
